Add debug symbols flag.

diff --git a/lambda b/lambda
--- a/lambda
+++ b/lambda
@@ -44,7 +44,13 @@ if test -f "$INPUT"; then
   case "$OUTPUT" in
     "")
       # Dump assembly to stdout.
-      (cd "$DIR" || exit; dune exec ./main.exe -- -"$ARCH" "$INPUT")
+        if ! (
+                cd "$DIR" || exit 1
+                dune exec ./main.exe -- $FLAGS -"$ARCH" "$INPUT"
+            ); then
+            echo "Failed to compile."
+            exit 1
+        fi
       ;;
     *)
       # Create a temporary directory.
@@ -52,13 +58,19 @@ if test -f "$INPUT"; then
 
       # Compile and link.
       if ! (
-              set -e
-              (cd "$DIR" || exit 1; dune exec ./main.exe -- -"$ARCH" "$INPUT" -o "$WORK_DIR/lambda.S")
+              if ! (
+                      cd "$DIR" || exit 1
+                      dune exec ./main.exe -- $FLAGS -"$ARCH" "$INPUT" -o "$WORK_DIR/lambda.S"
+                  ); then
+                  echo "Failed to compile."
+                  exit 1
+              fi
+
               gcc -c runtime_x86_64.S -o "$WORK_DIR/runtime.o"
               gcc $FLAGS "$WORK_DIR/lambda.S" "$WORK_DIR/runtime.o" -o "$OUTPUT"
           ); then
           echo "Failed to build."
-          exit 1;
+          exit 1
       fi
 
       # Cleanup temp directory.
