Streamline testing.

diff --git a/lambda b/lambda
--- a/lambda
+++ b/lambda
@@ -1,7 +1,5 @@
 #!/usr/bin/bash
 
-set -e
-
 function realpath() {
     [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
 }
@@ -53,9 +51,15 @@ if test -f "$INPUT"; then
       WORK_DIR=$(mktemp -d)
 
       # Compile and link.
-      (cd "$DIR" || exit 1; dune exec ./main.exe -- -"$ARCH" "$INPUT" -o "$WORK_DIR/lambda.S")
-      gcc -c runtime_x86_64.S -o "$WORK_DIR/runtime.o"
-      gcc $FLAGS "$WORK_DIR/lambda.S" "$WORK_DIR/runtime.o" -o "$OUTPUT"
+      if ! (
+              set -e
+              (cd "$DIR" || exit 1; dune exec ./main.exe -- -"$ARCH" "$INPUT" -o "$WORK_DIR/lambda.S")
+              gcc -c runtime_x86_64.S -o "$WORK_DIR/runtime.o"
+              gcc $FLAGS "$WORK_DIR/lambda.S" "$WORK_DIR/runtime.o" -o "$OUTPUT"
+          ); then
+          echo "Failed to build."
+          exit 1;
+      fi
 
       # Cleanup temp directory.
       if test -z $FLAGS; then
