Move source into new directory.

diff --git a/lambda b/lambda
--- a/lambda
+++ b/lambda
@@ -19,6 +19,7 @@ ARCH=$(uname -m)
 
 # Parse the arguments.
 OUTPUT=""
+INTERP_LEVEL=""
 while getopts "h?gi:o:" opt; do
     case "$opt" in
     h|\?)
@@ -30,6 +31,7 @@ while getopts "h?gi:o:" opt; do
         ;;
     i)
         FLAGS="${FLAGS:+$FLAGS }-i $OPTARG"
+        INTERP_LEVEL=$OPTARG
         ;;
     o)
         OUTPUT=$OPTARG
@@ -41,6 +43,11 @@ shift $((OPTIND-1))
 
 [ "${1:-}" = "--" ] && shift
 
+if test -n "$OUTPUT" && test -n "$INTERP_LEVEL"; then
+    echo "Cannot compile and interpret."
+    exit 9
+fi
+
 # Find the input file.
 INPUT=$(realpath "$1")
 if test -f "$INPUT"; then
@@ -49,7 +56,7 @@ if test -f "$INPUT"; then
     "")
       # Dump assembly to stdout.
         if ! (
-                cd "$DIR" || exit 1
+                cd "$DIR/src" || exit 1
                 dune exec ./main.exe -- $FLAGS -"$ARCH" "$INPUT"
             ); then
             echo "Failed to compile."
@@ -63,14 +70,14 @@ if test -f "$INPUT"; then
       # Compile and link.
       if ! (
               if ! (
-                      cd "$DIR" || exit 1
+                      cd "$DIR/src" || exit 1
                       dune exec ./main.exe -- $FLAGS -"$ARCH" "$INPUT" -o "$WORK_DIR/lambda.S"
                   ); then
                   echo "Failed to compile."
                   exit 1
               fi
 
-              gcc -c runtime_x86_64.S -o "$WORK_DIR/runtime.o"
+              gcc -c asm/runtime_x86_64.S -o "$WORK_DIR/runtime.o"
               gcc $FLAGS "$WORK_DIR/lambda.S" "$WORK_DIR/runtime.o" -o "$OUTPUT"
           ); then
           echo "Failed to build."
